### ISSUE TITLE
Problem parsing date with offset

### ISSUE THREAD

**Issue by davidkarlsen** [migesok/jaxb-java-time-adapters#4]
I have problems parsing a date which has offset from UTC as described below:

package com.edb.fs.tac.jfr.srv.service;

import com.edb.fs.tac.jfr.srv.test.AbstractTest;
import com.migesok.jaxb.adapter.javatime.InstantXmlAdapter;
import com.migesok.jaxb.adapter.javatime.LocalDateXmlAdapter;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import javax.xml.bind.annotation.adapters.XmlAdapter;

/**
 * Created by et2448 on 3/13/15.
 */
public class TestTest
    extends AbstractTest
{
    private XmlAdapter xmlAdapter;

    @Before
    public void before() {
        this.xmlAdapter = new LocalDateXmlAdapter();
        //this.xmlAdapter = new InstantXmlAdapter();
    }

//this test will break:
    @Test
    public void testParseWithOffset() throws Exception {
        String input = "1988-01-08+01:00";
        xmlAdapter.unmarshal( input );
    }

    @Test
    public void testWithoutOffset() throws Exception  {
        String input = "1988-01-08";
        xmlAdapter.unmarshal( input );
    }
}

**Comment by migesok** [comment]
Thanks for the PR!
XSD date does not really have direct counterpart amongst JSR-310 types. LocalDate is here but it misses the time-zone information.
For me personally the whole concept of the "date to time-zone" pairing seems unnatural but that's how XSD temporals are made. So it is a good idea to be prepared and keep the LocalDate unmarshalling lax enough to accommodate it.

**Comment by migesok** [comment]
I am going to publish the next release with the changes on weekend so it will definitely land on Maven Central by Monday.
